# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AbZb1yPjG4kAWM26yO72nicBacMPOxI3
"""

import pandas as pd

data = pd.read_csv('/content/auto-mpg[1].csv')

data.head()

data.dtypes

from sklearn.preprocessing import LabelEncoder
categorical_cols = data.select_dtypes(include=['object']).columns
label_encoders = {}
for col in categorical_cols:
    label_encoders[col] = LabelEncoder()
    data[col] = label_encoders[col].fit_transform(data[col])

data.head()

data.isnull().sum()

data.fillna(data.mean(), inplace=True)

"""# Apply machine Learning"""

x = data.drop(columns=['mpg'])
y = data['mpg']

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

prediksi = model.predict([[8,307,15,3504,12,70,1,49]])
print(" mpg prediction", round(prediksi[0], 2))